version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    container_name: ${APP_NAME}_wordpress
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - ./wordpress_data:/var/www/html
    networks:
      - wp_network

  mariadb:
    image: mariadb:latest
    container_name: ${APP_NAME}_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mariadb_data:/var/lib/mysql
      - ./mariadb-init:/docker-entrypoint-initdb.d
    networks:
      - wp_network

  nginx:
    image: nginx:latest
    container_name: ${APP_NAME}_nginx
    depends_on:
      - wordpress
    volumes:
      - ./nginx/nginx.template:/etc/nginx/nginx.template
      - ./certs:/etc/nginx/certs
      - ./wordpress_data:/var/www/html
      - ./nginx/entrypoint.sh:/entrypoint.sh
    environment:
      - SITE_URL=${SITE_URL}
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    ports:
      - "80:80"
      - "443:443"
    networks:
      - wp_network

networks:
  wp_network: